### About

POST {{BASE}}/browse
Content-Type: application/json
X-Goog-Api-Key: {{KEY}}


{
	"context": {
		"client": {
			"hl": "en",
			"gl": "US",
			"clientName": "WEB",
			"clientVersion": "2.20210701.07.00"
		}
	},
	"browseId": "UCJwGWV914kBlV4dKRn7AEFE",
	"params": "EgVhYm91dA%3D%3D"
}

### Videos

POST {{BASE}}/browse
Content-Type: application/json
X-Goog-Api-Key: {{KEY}}

{
	"context": {
		"client": {
			"hl": "en",
			"gl": "US",
			"clientName": "WEB",
			"clientVersion": "2.20210701.07.00"
		}
	},
	"browseId": "UCJwGWV914kBlV4dKRn7AEFA",
	"params": "EgZ2aWRlb3M%3D"
}

### Playlists

POST {{BASE}}/browse
Content-Type: application/json
X-Goog-Api-Key: {{KEY}}

{
	"context": {
		"client": {
			"hl": "en",
			"gl": "US",
			"clientName": "WEB",
			"clientVersion": "2.20210701.07.00"
		}
	},
	"browseId": "UCJwGWV914kBlV4dKRn7AEFA",
	"params": "EglwbGF5bGlzdHM%3D"
}

### Channels

POST {{BASE}}/browse
Content-Type: application/json
X-Goog-Api-Key: {{KEY}}

{
	"context": {
		"client": {
			"hl": "en",
			"gl": "US",
			"clientName": "WEB",
			"clientVersion": "2.20210701.07.00"
		}
	},
	"browseId": "UCJwGWV914kBlV4dKRn7AEFA",
	"params": "EghjaGFubmVscw%3D%3D"
}

### Community

POST {{BASE}}/browse
Content-Type: application/json
X-Goog-Api-Key: {{KEY}}

{
	"context": {
		"client": {
			"hl": "en",
			"gl": "US",
			"clientName": "WEB",
			"clientVersion": "2.20210701.07.00"
		}
	},
	"browseId": "UCJwGWV914kBlV4dKRn7AEFA",
	"params": "Egljb21tdW5pdHk%3D"
}


### Store

POST {{BASE}}/browse
Content-Type: application/json
X-Goog-Api-Key: {{KEY}}

{
	"context": {
		"client": {
			"hl": "en",
			"gl": "US",
			"clientName": "WEB",
			"clientVersion": "2.20210701.07.00"
		}
	},
	"browseId": "UCJwGWV914kBlV4dKRn7AEFA",
	"params": "EgVzdG9yZQ%3D%3D"
}


